### PR TITLE
Issue/940

### PR DESCRIPTION
**Pull request by ryuuzake**
Resolves https://github.com/aehrc/smart-forms/issues/940.

### CODE REVIEW

**Comment by ryuuzake** [comment]
Storybook and Smart Forms Playground Proves

| Storybook                                                                                 | Playground                                                                                |
|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| image | image |
| image | image |
| image | image |

**Comment by fongsean** [comment]
I went though the changes and they look really good!

I really love the bit (see image) where if a renderer does not support the "page" extension, it will render a normal group as usual. And having it isolated and not affecting the other items is great.

image

I think the current design is good - I have minimal changes to make which makes the FAB more consistent with the tab buttons: https://github.com/konsulin-id/smart-forms/compare/issue/940...aehrc%3Asmart-forms%3Aissue/940

Can you have a look and see if they are appropriate? If they are, you can merge in those changes into your branch and it will appear in this PR.

**Comment by ryuuzake** [comment]
I think your changes is appropriate, I'll merge it into my branch to update this PR

**Comment by ryuuzake** [comment]
@fongsean there's a conflict for the `package-lock.json` should I merge update from `main` branch or do you have any other suggestion?

**Comment by fongsean** [comment]
Yep, you should be able to merge in the package-lock.json from main. 

You can fully accept the one from main, then run `npm i`. There should be some new changes in package-lock.json. Commit those changes as a new commit and it should be solved.

**Comment by ryuuzake** [comment]
done resolving the `package-lock.json` conflict

**Review by fongsean — APPROVED** [review]
Looks great. You are our first contributor 🤩🤩🤩

**Pull request merged**
