### PR TITLE
Issue/639

### LINKED ISSUE #639: Build reference and quantity components
The renderer is still yet unable to render items of type = "reference" and "quantity".

The "Bit of everything" questionnaire provides a simple example of how these items look like.

### PR DESCRIPTION
**Pull request by ryuuzake**
Resolves #639 

Here some proves that the components works

| Storybook                                                                                 | Playground                                                                                |
|-------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------|
| image | image |

### CODE REVIEW

**Comment by fongsean** [comment]
Hi @ryuuzake, just providing some updates:

I have added some changes to handle initial/pre-pop in https://github.com/aehrc/smart-forms/commits/issue/639/.


After that I also want to add changes so that it works with calculatedExpression with unit - handling of Quantity datatype in fhirpath http://hl7.org/fhirpath/N1/#quantity. I can't quite finish it today, hopefully I get to finish it tomorrow.

**Comment by fongsean** [comment]
Hi @ryuuzake,

See https://github.com/konsulin-id/smart-forms/compare/issue/639...aehrc:smart-forms:issue/639

I've added the following changes:
1. Added optional comparator field
2. Added code to handle pre-population of quantity elements (comparator, value, unit)
3. Added a whole new hook for managing calculation expressions in Quantity components
4. Added more Quantity stories for visual testing 

| Feature | Storybook    |
|------|------|
| Comparator field  |image |
| Calculation | image |

If it looks good, can you merge it into your branch? I'll give it one last review and merge it into `main` after.

**Comment by fongsean** [comment]
Oops, I forgot I will need to update the documentation as well.
I'll get it done at the end of today.

**Comment by fongsean** [comment]
Added documentation for the Quantity component.

I've merged main into this branch a couple times now, so the conflicts might get nasty.
Hopefully the conflicts are all in package.json and package-lock.json. If thats the case, you can accept right and run `npm i` again. 

Let me know how it goes and I'll see if there's an alternative solution.

**Comment by ryuuzake** [comment]
Hi @fongsean

I'll try to check on the changes later tonight. If everything checks out, I'll resolve the conflict and merge it.

Hopefully this PR can soon be accepted to the `main` branch

**Comment by ryuuzake** [comment]
Hi @fongsean 
Sorry for the slow response. I already merge your changes to this PR

**Comment by fongsean** [comment]
Thanks @ryuuzake!

**Pull request merged**
